---
title: "Simulated-data MFPCA"
output:
    pdf_document
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = FALSE, message = F)
```


```{r , echo = FALSE, message = FALSE}

rm(list=ls())

library(refund)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(reshape2)

#load simulated data
load("./data/simul_dat.rda")

#apply mfpca function from refund package
pve=0.9

#this may take hours to days depends on the machine
m = mfpca.sc(Y=simul_dat, id = ID[,1] , twoway = TRUE,pve=pve) 

bout.max=60
boutID=readRDS("./data/boutID.rds")

```


```{r , echo = FALSE, message = FALSE}
#refund package also provided a small sample data, details see
#https://cran.r-project.org/web/packages/refund/refund.pdf

# data(DTI)
# DTI = subset(DTI, Nscans < 6) ## example where all subjects have 6 or fewer visits
# id = DTI$ID
# Y = DTI$cca
# mfpca.DTI = mfpca.sc(Y=Y, id = id, twoway = TRUE)
```



\section{Level 1}
```{r , echo = FALSE, message = FALSE, fig.width = 14, fig.height = 12}

#=================================================================== 
#level1
#===================================================================
prop1=m$evalues$level1/sum(m$evalues$level1)
cat("Eigenvalues:",round(m$evalues$level1,3))
cat("Eigenvalue proportions:",round(prop1,3),"\n")
efcn1=melt(m$efunctions$level1,
           value.name="eigenfunctions"
 )

npc1=m$npc$level1

#create label that will be on the top of the plot
l5=data.frame(cbind(bout_len=1:bout.max,cumBout_len=cumsum(1:bout.max)))
ind=seq_len(nrow(l5)) %% 10
l5=l5[ind==0,]##only take every 10


gg1=list()

#eigenfcn:
gg1[[1]]=ggplot(data=efcn1,aes(x=Var1,y=eigenfunctions))+geom_line(size=0.5)+labs(y="",title="")+scale_x_continuous(name="",labels=rep("",length(l5$cumBout_len)), breaks=l5$cumBout_len,sec.axis =  dup_axis(labels=l5$bout_len, name = 'Individual bout length (unit:minute)'))+geom_vline(data=boutID,
              aes(xintercept = boutCut),
               colour = "grey",size=0.2)+
  theme_bw()+facet_wrap(~Var2,ncol= m$npc$level1)+theme(strip.background = element_rect(fill = "white"), axis.title.x = element_text(size=15))


dat2 <- data.frame(sweep(m$efunctions$level1,MARGIN=2,sqrt(m$evalues$level1),"*")[,1:m$npc$level1])
dat2$mu=m$mu 


for(i in 1:m$npc$level1){
  varl=paste0("mu",i,"_lwr")
  varU= paste0("mu",i,"_upr")
  varX= rlang::sym(paste0("X",i))
  dat2=dat2%>%mutate(!!varl := mu - (!!varX), !!varU := mu + (!!varX))
}

dat2=dat2[,which(grepl("mu",colnames(dat2)))]
dat2$timeSeq=as.numeric(rownames(dat2))

dat2l=NULL
for (i in 1:m$npc$level1){
  vars=c("mu",paste0("mu",i,"_lwr"),paste0("mu",i,"_upr"))
  dt=dat2[,c("timeSeq",vars)] %>% tidyr::gather(v, value,2:4)%>%dplyr::mutate(component=i)
  d=dt%>%distinct(v)
  d$type=rownames(d)
  d$type=factor(d$type,levels=1:3,labels=c("mu","-","+"))
  dt=merge(dt,d,by="v",all.x=T)
  dat2l=rbind(dat2l,dt)
}


#mu and variance
gg1[[2]]=ggplot(data=dat2l,aes(x=timeSeq,y=value,color=type))+geom_vline(data=boutID,
              aes(xintercept = boutCut),
               colour = "grey",size=0.2)+
  geom_line(size=0.5)+scale_color_discrete(name="",labels=c(expression(mu(t)),"-","+"))+
  labs(y="Simulated outcome",title = "",x="")+scale_x_continuous(name="",labels=rep("",length(l5$cumBout_len)), breaks=l5$cumBout_len,sec.axis =  dup_axis(labels=l5$bout_len, name = ''))+
  theme_bw()+
  geom_line(size=0.5)+ 
    theme(legend.position="bottom",
          legend.title=element_blank(),
          axis.text=element_text(size=8)
          )+
  facet_wrap(~component,ncol=m$npc$level1)+theme(strip.background = element_rect(fill = "white"))


grid.arrange(gg1[[1]],gg1[[2]],nrow=2)

```


\newpage

\section{Level 2}


```{r , echo = FALSE, message = FALSE, fig.width = 14, fig.height = 12}
#=================================================================== 
#level2
#===================================================================
npc2=m$npc$level2
prop2=m$evalues$level2/sum(m$evalues$level2)
cat("Eigenvalues:",round(m$evalues$level2,2)[1:npc2])
r=round(prop2,2)[1:npc2]
tmp=data.frame(Var2=1:npc2,r=r)
cat("Eigenvalue proportions:",r,"\n")

efcn2_5=melt(m$efunctions$level2[,1:npc2],
           value.name="eigenfunctions"
 )

rho=round(sum(m$evalues$level1[1:npc1])/(sum(m$evalues$level1[1:npc1])+sum(m$evalues$level2[1:npc2])),3)
cat("Proportion of variability explained by level 1 components:",rho,"\n")
cat("Proportion of variability explained by level 2 components:",1-rho,"\n")
cat("(",npc1,"components at level 1 and", npc2,"components at level 2) explain at least", pve, "of total variability.")


efcn2_5=merge(efcn2_5,tmp,by="Var2")%>%dplyr::mutate(comp_lab=paste0(Var2," (",r*100,"%)"))

gg2_5=list()

#eigenfcn
gg2_5[[1]]=ggplot(data=efcn2_5,aes(x=Var1,y=eigenfunctions))+geom_line(size=0.5)+labs(y="",title="")+scale_x_continuous(name="",labels=rep("",length(l5$cumBout_len)), breaks=l5$cumBout_len,sec.axis =  dup_axis(labels=l5$bout_len, name = 'Individual bout length (unit:minute)'))+geom_vline(data=boutID,
              aes(xintercept = boutCut),
               colour = "grey",size=0.2)+
  theme_bw()+facet_wrap(~comp_lab,ncol= npc2)+theme(strip.background = element_rect(fill = "white"), axis.title.x = element_text(size=15))

#mu(t) +/-
dat2_5 <- data.frame(sweep(m$efunctions$level2[,1:npc2],MARGIN=2,sqrt(m$evalues$level2[1:npc2]),"*")[,1:npc2])
dat2_5$mu=m$mu
for(i in 1:npc2){
  varl=paste0("mu",i,"_lwr")
  varU= paste0("mu",i,"_upr")
  varX= rlang::sym(paste0("X",i))
  dat2_5=dat2_5%>%mutate(!!varl := mu - (!!varX), !!varU := mu + (!!varX))
}

dat2_5=dat2_5[,which(grepl("mu",colnames(dat2_5)))]
dat2_5$timeSeq=as.numeric(rownames(dat2_5))

dat2l=NULL
for (i in 1:npc2){
  vars=c("mu",paste0("mu",i,"_lwr"),paste0("mu",i,"_upr"))
  dt=dat2_5[,c("timeSeq",vars)] %>% tidyr::gather(v, value,2:4)%>%dplyr::mutate(component=i)
  d=dt%>%distinct(v)
  d$type=rownames(d)
  d$type=factor(d$type,levels=1:3,labels=c("mu","-","+"))
  dt=merge(dt,d,by="v",all.x=T)
  dat2l=rbind(dat2l,dt)
}

gg2_5[[2]]=ggplot(data=dat2l,aes(x=timeSeq,y=value,color = type))+geom_vline(data=boutID,
              aes(xintercept = boutCut),
               colour = "grey",size=0.2)+
  geom_line(size=0.5)+scale_color_discrete(name="",labels=c(expression(mu(t)),"-","+"))+
  labs(y="Simulated outcome",title = "",x="")+scale_x_continuous(name="",labels=rep("",length(l5$cumBout_len)), breaks=l5$cumBout_len,sec.axis =  dup_axis(labels=l5$bout_len, name = ''))+
  theme_bw()+
  geom_line(size=0.5)+ 
    theme(legend.position="bottom",
          legend.title=element_blank(),
          axis.text=element_text(size=8)
          )+
  facet_wrap(~component,ncol=npc2)+theme(strip.background = element_rect(fill = "white"))

  grid.arrange(gg2_5[[1]],gg2_5[[2]],nrow=2)

```
\newpage

\section{Example of a fitted curves}
```{r echo = FALSE, message = FALSE, fig.height= 4, fig.width=12}
#========================
#pick one
#100433 11/11/2019, day4
#========================
Y=simul_dat
id="100433";wearDate="2019-11-11";d=4;
indx=which(ID[,1]==id & ID[,2]==wearDate)#index among subject-visit;
indx2=which(unique(ID[,1])==id) #index among subject
ll=data.frame(cbind(bout_len=1:bout.max,cumBout_len=cumsum(1:bout.max)))%>%dplyr::mutate(bout_indx=1-bout_len%%2)
ll$bout_indx[c(2:7,10,14)]=0
ll$bout_indx[1]=1
ll=ll%>%dplyr::mutate(bout_len=ifelse(bout_indx==0,NA,bout_len),breaks=ifelse(bout_indx==0,NA,cumBout_len))
cumBout_len=1:length(m$mu)

#use component chosen at level 1 and 2
tmp=data.frame(ID=id,wearDate=wearDate,cumBout_len=cumBout_len,mu=m$mu,eta=m$eta[,d],obs=Y[indx,])%>%
  dplyr::mutate(mu_eta=mu+eta,level1pc=t(m$scores$level1[indx2,1:npc1]%*%t(m$efunctions$level1[,1:npc1]))[,1],
                level2pc=t(m$scores$level2[indx,1:npc2]%*%t(m$efunctions$level2[,1:npc2]))[,1],
                val.subject=mu+eta+level1pc,
                val.hat=mu+eta+level1pc+level2pc,
                Yhat.subject=m$Yhat.subject[indx,],Yhat=m$Yhat[indx,]) #Yhat.subject and Yhat are from mfpca.sc output
val=merge(tmp,ll,by="cumBout_len",all=T)

#wide to long
dd_long=melt(val, id.vars=c("ID","cumBout_len","bout_len","breaks"),measure.vars=c("obs","mu", "mu_eta", "val.subject","val.hat"),
    variable.name="type",
    value.name="value"
)
dd=dd_long%>%filter(type != "obs")

g=ggplot(data=dd,aes(x=cumBout_len,y=value,color = type))+geom_vline(data=boutID,
              aes(xintercept = boutCut),
               colour = "grey",size=0.2)+
  geom_line(size=0.5)+scale_color_discrete(name="",labels=c(1,2,3,4))+
  geom_point(data=dd_long%>%filter(type == "obs"), aes(x = cumBout_len, y = value), size = 0.5, color = "black")+
  labs(y="Simulated outcome",title = "")+scale_x_continuous(name="",labels=rep("",length(dd$cumBout_len)), breaks=dd$breaks,sec.axis =  dup_axis(labels=dd$bout_len, name = ''))+
  theme_bw()+
  theme(plot.title = element_text(size=15, face="bold"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_text(size=10),
    text = element_text(size=15),panel.grid.minor = element_blank(),legend.position="bottom",
    legend.title=element_blank(),legend.text=element_text(size=10),legend.text.align=0)

print(g)


```